sudo: false
osx_image: xcode7.2

language: objective-c
#before_install:
#   - brew unlink xctool
#    - brew update
#    - brew install xctool
script:
- xctool -workspace Example/DovMess.xcworkspace -scheme DovMess-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace Example/DovMess.xcworkspace -scheme DovMess_Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO